# Generated by Django 5.1.1 on 2024-10-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
