# Generated by Django 5.1.2 on 2024-10-11 06:28

import apps.chapter.models
import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('audio', models.FileField(upload_to=apps.chapter.models.get_chapter_audio_upload_path)),
                ('duration', models.PositiveIntegerField(help_text='Duration of the chapter in seconds.', validators=[django.core.validators.MinValueValidator(1)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book.book')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
