# Generated by Django 5.1.1 on 2024-10-08 14:05

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models

import apps.chapter.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('chapterId', models.AutoField(primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to=apps.chapter.models.get_chapter_audio_upload_path)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters',
                                           to='book.book')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
