# Generated by Django 5.1.2 on 2024-10-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
